import {
  CoupleProfile,
  Guest,
  Household,
  Task,
  Vendor,
  BudgetItem,
  Payment,
  Palette,
  Outfit,
  Venue,
  Table,
  Seat,
  TimelineItem,
  Document,
  Gift,
  PhotoShot,
  ActivityLog,
  Notification
} from '../types';

export const DEMO_WORKSPACE_ID = 'demo-workspace-modelo';

export const demoCoupleProfile: CoupleProfile = {
  workspaceId: DEMO_WORKSPACE_ID,
  partner1Name: 'Alex Silva',
  partner2Name: 'Taylor Santos',
  coverImageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
  weddingDate: '2027-10-23',
  weddingTime: '16:30',
  timezone: 'America/Sao_Paulo',
  city: 'São Paulo',
  state: 'SP',
  weddingType: 'civil_e_religioso',
  estimatedGuestsCount: 180,
  totalBudgetPlanned: 135000,
  financialResponsibles: ['Casal (60%)', 'Família Partner 1 (25%)', 'Família Partner 2 (15%)'],
  style: 'Botânico Chic & Sofisticado',
  formalityLevel: 'Semi-Formal',
  priorities: ['Gastronomia & Open Bar', 'Fotografia & Filmagem', 'Música & Pista Viva', 'Decoração Floral'],
  culturalTraditions: 'Cerimônia das Areias e Bênção das Alianças',
  accessibilityNeeds: 'Rampa de acesso ao altar e 2 convidados cadeirantes com mesas próximas ao banheiro acessível',
  availableWeeklyHours: 8,
  customSlug: 'alex-taylor-demo',
  status: 'active',
};

export const demoPalette: Palette = {
  workspaceId: DEMO_WORKSPACE_ID,
  colors: [
    {
      id: 'c1',
      name: 'Marsala Profundo',
      hex: '#8B263E',
      rgb: '139, 38, 62',
      role: 'principal',
      appliedTo: ['Flores do Altar', 'Detalhes da Papelaria', 'Laços dos Guardanapos'],
    },
    {
      id: 'c2',
      name: 'Dusty Rose / Rosa Antigo',
      hex: '#C48B9F',
      rgb: '196, 139, 159',
      role: 'secundaria',
      appliedTo: ['Vestidos das Madrinhas', 'Arranjos da Mesa de Doces', 'Velas da Recepção'],
    },
    {
      id: 'c3',
      name: 'Grafite Carvão',
      hex: '#1E293B',
      rgb: '30, 41, 59',
      role: 'acento',
      appliedTo: ['Terno Principal', 'Tipografia dos Convites', 'Estrutura dos Lustres'],
    },
    {
      id: 'c4',
      name: 'Azul-Marinho Clássico',
      hex: '#1A2536',
      rgb: '26, 37, 54',
      role: 'secundaria',
      appliedTo: ['Trajes dos Padrinhos', 'Gravatas', 'Toalhas da Mesa dos Pais'],
    },
    {
      id: 'c5',
      name: 'Verde Sálvia',
      hex: '#5B7065',
      rgb: '91, 112, 101',
      role: 'neutra',
      appliedTo: ['Foliagens de Eucalipto', 'Fundo do Site Público', 'Menus das Mesas'],
    },
    {
      id: 'c6',
      name: 'Amarelo Neon Proibido',
      hex: '#FFFF00',
      rgb: '255, 255, 0',
      role: 'proibida',
      appliedTo: ['Nenhum elemento decorativo'],
    },
  ],
  primaryTypography: 'Playfair Display',
  secondaryTypography: 'Plus Jakarta Sans',
  photoStyleDescription: 'Fotografia com iluminação natural acolhedora, tons quentes e poéticos, estilo fotojornalístico documental.',
  texturesAndMaterials: ['Linho puro cru', 'Madeira nobre de demolição', 'Metais em dourado fosco', 'Velas de cera vegetal'],
  visualVoiceTone: 'Romântico, acolhedor, sofisticado sem ostentação e extremamente inclusivo.',
};

export const demoVenues: Venue[] = [
  {
    id: 'v1',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Espaço Celebração & Gastronomia',
    type: 'ambos',
    address: 'Av. das Alamedas, 1200 - Jardins',
    city: 'São Paulo',
    state: 'SP',
    seatedCapacity: 220,
    standingCapacity: 300,
    hasParking: true,
    valetAvailable: true,
    restroomsCount: 8,
    hasNursery: true,
    hasKitchen: true,
    hasDressingRoom: true,
    generatorPowerKva: 150,
    airConditioning: true,
    accessibleRoute: true,
    weatherBackupPlan: 'Pergola envidraçada climatizada integrada para a cerimônia em caso de chuva forte.',
    noiseRestrictions: 'Som reduzido após às 03:00h.',
    rentalFee: 24000,
    notes: 'Local com jardim amplo e suíte para preparação dos noivos.',
  },
];

export const demoOutfits: Outfit[] = [
  {
    id: 'o1',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Alex Silva (Noiva / Noivo)',
    role: 'noiva',
    color: 'Off-White Ivory',
    itemDescription: 'Traje fluído em zibelina de seda com decote ombro a ombro e cauda removível',
    rentalOrBuy: 'compra',
    totalCost: 9800,
    paidBy: 'Casal',
    sizesAndMeasurements: 'Ajuste sob medida cadastrado no ateliê',
    status: 'em_ajuste',
    imageUrl: 'https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&w=600&q=80',
    accessoriesNotes: 'Véu de tule francês 3m com aplicação de renda guipure',
  },
  {
    id: 'o2',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Taylor Santos (Noivo / Noiva)',
    role: 'noivo',
    color: 'Carvão Grafite',
    itemDescription: 'Terno slim fit sob medida em lã fria Super 130s com colete e camisa de algodão egípcio',
    rentalOrBuy: 'compra',
    totalCost: 4500,
    paidBy: 'Casal',
    sizesAndMeasurements: 'Terno 48L | Camisa 3 | Sapato 41',
    status: 'pronto',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    accessoriesNotes: 'Gravata borboleta marsala + Abotoaduras em prata',
  },
  {
    id: 'o3',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Madrinhas (8 participantes)',
    role: 'madrinha',
    color: 'Dusty Rose / Rosa Antigo (#C48B9F)',
    itemDescription: 'Vestidos longos no tom rosa antigo (modelo livre à escolha)',
    rentalOrBuy: 'proprio',
    totalCost: 0,
    paidBy: 'Madrinhas',
    sizesAndMeasurements: 'Guia de tons entregue no Manual dos Padrinhos',
    status: 'escolhido',
    accessoriesNotes: 'Corsage floral idêntico fornecido pelo cerimonial',
  },
  {
    id: 'o4',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Padrinhos (8 participantes)',
    role: 'padrinho',
    color: 'Azul-Marinho Clássico (#1A2536)',
    itemDescription: 'Terno completo azul-marinho + Camisa branca + Gravata marsala padronizada',
    rentalOrBuy: 'aluguel',
    totalCost: 2400,
    paidBy: 'Padrinhos',
    sizesAndMeasurements: 'Aluguel em loja parceira de alfaiataria',
    status: 'escolhido',
    accessoriesNotes: 'Gravata marsala presenteada pelo casal',
  },
];

export const demoHouseholds: Household[] = [
  { id: 'h1', workspaceId: DEMO_WORKSPACE_ID, familyName: 'Família Silva (Exemplo)', city: 'São Paulo - SP' },
  { id: 'h2', workspaceId: DEMO_WORKSPACE_ID, familyName: 'Família Santos (Exemplo)', city: 'Campinas - SP' },
  { id: 'h3', workspaceId: DEMO_WORKSPACE_ID, familyName: 'Casal Padrinhos Lucas & Camila', city: 'São Paulo - SP' },
];

export const demoGuests: Guest[] = [
  {
    id: 'g1',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h1',
    fullName: 'Roberto Silva',
    relationship: 'familia_noiva',
    category: 'pais',
    phone: '(11) 99999-0001',
    email: 'roberto.silva@exemplo.example',
    ageType: 'adulto',
    invitationType: 'familiar',
    allowedPlusOnes: 1,
    plusOneNames: ['Helena Silva'],
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's1',
    qrCodeToken: 'QR-SILVA-ROBERTO-001',
    checkedIn: false,
    notes: 'Pai do noivo(a) - discurso no brinde.',
  },
  {
    id: 'g2',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h1',
    fullName: 'Helena Silva',
    relationship: 'familia_noiva',
    category: 'pais',
    phone: '(11) 99999-0002',
    email: 'helena.silva@exemplo.example',
    ageType: 'adulto',
    invitationType: 'familiar',
    allowedPlusOnes: 0,
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's2',
    qrCodeToken: 'QR-SILVA-HELENA-002',
    checkedIn: false,
    notes: 'Mãe do noivo(a) - restrição a frutos do mar.',
  },
  {
    id: 'g3',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h2',
    fullName: 'Carlos Eduardo Santos',
    relationship: 'familia_noivo',
    category: 'pais',
    phone: '(19) 99999-0003',
    email: 'carlos.santos@exemplo.example',
    ageType: 'adulto',
    invitationType: 'familiar',
    allowedPlusOnes: 1,
    plusOneNames: ['Márcia Santos'],
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's3',
    qrCodeToken: 'QR-SANTOS-CARLOS-003',
    checkedIn: false,
  },
  {
    id: 'g4',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h3',
    fullName: 'Lucas Gabriel',
    relationship: 'amigos',
    category: 'padrinho',
    phone: '(11) 99999-0004',
    email: 'lucas.gabriel@exemplo.example',
    ageType: 'adulto',
    invitationType: 'individual',
    allowedPlusOnes: 1,
    plusOneNames: ['Camila Rocha'],
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't2',
    seatId: 's5',
    qrCodeToken: 'QR-LUCAS-GABRIEL-004',
    checkedIn: false,
    notes: 'Padrinho - opção vegetariana.',
  },
  {
    id: 'g5',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h3',
    fullName: 'Camila Rocha',
    relationship: 'amigos',
    category: 'madrinha',
    phone: '(11) 99999-0005',
    email: 'camila.rocha@exemplo.example',
    ageType: 'adulto',
    invitationType: 'individual',
    allowedPlusOnes: 0,
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't2',
    seatId: 's6',
    qrCodeToken: 'QR-CAMILA-ROCHA-005',
    checkedIn: false,
    notes: 'Madrinha.',
  },
  {
    id: 'g6',
    workspaceId: DEMO_WORKSPACE_ID,
    fullName: 'Dona Beatris Silva',
    relationship: 'familia_noiva',
    category: 'vip',
    phone: '(11) 99999-0006',
    ageType: 'adulto',
    invitationType: 'individual',
    allowedPlusOnes: 0,
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's4',
    qrCodeToken: 'QR-BEATRIS-SILVA-006',
    checkedIn: false,
    notes: 'Avó - necessita de rampa de acesso e assento estofado confortável.',
  },
];

export const demoTables: Table[] = [
  {
    id: 't0',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Mesa Imperial dos Noivos',
    shape: 'imperial',
    capacity: 2,
    posX: 50,
    posY: 20,
    zone: 'noivos',
  },
  {
    id: 't1',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Mesa 01 - Pais & Avós',
    shape: 'redonda',
    capacity: 8,
    posX: 25,
    posY: 40,
    zone: 'salao_principal',
  },
  {
    id: 't2',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Mesa 02 - Padrinhos & Madrinhas',
    shape: 'retangular',
    capacity: 10,
    posX: 75,
    posY: 40,
    zone: 'pista',
  },
];

export const demoTasks: Task[] = [
  {
    id: 'tk1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Fechar contrato do Espaço & Buffet Fictício',
    category: 'Local & Gastronomia',
    assignedToUserIds: ['user-1'],
    startDate: '2026-11-01',
    dueDate: '2026-12-15',
    priority: 'urgente',
    status: 'concluida',
    estimatedCost: 65000,
    subtasks: [
      { id: 'st1', title: 'Degustação do menu de 4 tempos', completed: true },
      { id: 'st2', title: 'Conferir cláusulas de chuva no plano B', completed: true },
      { id: 'st3', title: 'Assinar contrato digital', completed: true },
    ],
    attachmentsCount: 2,
    commentsCount: 4,
    monthsBeforeWedding: 12,
  },
  {
    id: 'tk2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Aprovar identidade visual e disparar Save the Date',
    category: 'Papelaria & Design',
    assignedToUserIds: ['user-1', 'user-2'],
    startDate: '2027-02-01',
    dueDate: '2027-03-30',
    priority: 'alta',
    status: 'concluida',
    estimatedCost: 2800,
    subtasks: [
      { id: 'st4', title: 'Definir paleta Marsala/Dusty Rose/Grafite', completed: true },
      { id: 'st5', title: 'Aprovar arte no Estúdio de Identidade', completed: true },
      { id: 'st6', title: 'Enviar Save the Date via WhatsApp e E-mail', completed: true },
    ],
    attachmentsCount: 3,
    commentsCount: 2,
    monthsBeforeWedding: 8,
  },
  {
    id: 'tk3',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Prova do traje principal e teste de beleza',
    category: 'Vestuário & Beleza',
    assignedToUserIds: ['user-2'],
    startDate: '2027-07-10',
    dueDate: '2027-07-25',
    priority: 'alta',
    status: 'em_andamento',
    estimatedCost: 9800,
    subtasks: [
      { id: 'st7', title: 'Ajustar barra com sapato oficial', completed: false },
      { id: 'st8', title: 'Levar acessórios ao ateliê', completed: true },
      { id: 'st9', title: 'Teste de durabilidade da maquiagem', completed: false },
    ],
    attachmentsCount: 1,
    commentsCount: 1,
    monthsBeforeWedding: 3,
  },
  {
    id: 'tk4',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Definir lista final de músicas da cerimônia e festa',
    category: 'Música & Pista',
    assignedToUserIds: ['user-1'],
    startDate: '2027-08-01',
    dueDate: '2027-08-30',
    priority: 'media',
    status: 'em_pesquisa',
    estimatedCost: 8500,
    subtasks: [
      { id: 'st10', title: 'Escolher música de entrada dos noivos', completed: true },
      { id: 'st11', title: 'Criar playlist de proibições (No-Play List)', completed: false },
    ],
    attachmentsCount: 0,
    commentsCount: 3,
    monthsBeforeWedding: 2,
  },
];

export const demoVendors: Vendor[] = [
  {
    id: 'vd1',
    workspaceId: DEMO_WORKSPACE_ID,
    category: 'Espaço & Buffet',
    legalName: 'Espaço Celebração & Gastronomia LTDA',
    tradeName: 'Espaço Celebração Eventos',
    documentNumber: '00.000.000/0001-00',
    contactPerson: 'Juliana Camargo',
    phone: '(11) 99999-0010',
    email: 'contato@espacocelebracao.example',
    city: 'São Paulo - SP',
    status: 'contratado',
    rating: 5,
    pros: 'Gastronomia espetacular, equipe impecável e plano B coberto muito elegante.',
    cons: 'Exige gerador próprio acima de 100 kva (já incluso no orçamento).',
    emergencyPhone: '(11) 99999-0011',
  },
  {
    id: 'vd2',
    workspaceId: DEMO_WORKSPACE_ID,
    category: 'Fotografia & Filmagem',
    legalName: 'Lumina Arte Visual Ltda',
    tradeName: 'Lumina Fotografia Poética',
    documentNumber: '00.000.000/0001-01',
    contactPerson: 'Gabriel Resende',
    phone: '(11) 99999-0020',
    email: 'contato@luminafotografia.example',
    city: 'São Paulo - SP',
    status: 'contratado',
    rating: 5,
    pros: 'Estilo documental único, entregam prévia de 50 fotos em 48 horas.',
    emergencyPhone: '(11) 99999-0021',
  },
  {
    id: 'vd3',
    workspaceId: DEMO_WORKSPACE_ID,
    category: 'Decoração Floral',
    legalName: 'Estúdio Botânico Design Floral',
    tradeName: 'Botânica Arte & Festas',
    documentNumber: '00.000.000/0001-02',
    contactPerson: 'Marina Prado',
    phone: '(11) 99999-0030',
    email: 'marina@botanicadesign.example',
    city: 'São Paulo - SP',
    status: 'negociacao',
    rating: 4,
    pros: 'Trabalho minucioso com orquídeas e eucaliptos na paleta Marsala.',
  },
];

export const demoBudgetItems: BudgetItem[] = [
  {
    id: 'bi1',
    workspaceId: DEMO_WORKSPACE_ID,
    categoryId: 'cat-1',
    description: 'Locação do Espaço Celebração + Buffet Completo (180 pessoas)',
    vendorId: 'vd1',
    quantity: 180,
    unitPrice: 320,
    estimatedCost: 60000,
    negotiatedCost: 57600,
    contractedCost: 57600,
    paidAmount: 38400,
    payerName: 'Casal (60%)',
    notes: 'Incluso coquetel volante, jantar 4 tempos, bar de drinks clássicos e mesa de café.',
  },
  {
    id: 'bi2',
    workspaceId: DEMO_WORKSPACE_ID,
    categoryId: 'cat-2',
    description: 'Cobertura de Fotografia + Filme Teaser + Drone (2 fotógrafos + 2 videomakers)',
    vendorId: 'vd2',
    quantity: 1,
    unitPrice: 12500,
    estimatedCost: 13000,
    negotiatedCost: 12500,
    contractedCost: 12500,
    paidAmount: 7500,
    payerName: 'Família Partner 1',
  },
  {
    id: 'bi3',
    workspaceId: DEMO_WORKSPACE_ID,
    categoryId: 'cat-3',
    description: 'Projeto Decorativo Floral Completo (Altar, Mesas, Lounge & Iluminação Cênica)',
    vendorId: 'vd3',
    quantity: 1,
    unitPrice: 22000,
    estimatedCost: 25000,
    negotiatedCost: 22000,
    contractedCost: 22000,
    paidAmount: 5000,
    payerName: 'Casal',
  },
];

export const demoPayments: Payment[] = [
  {
    id: 'p1',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi1',
    vendorId: 'vd1',
    installmentNumber: 1,
    totalInstallments: 3,
    amount: 19200,
    dueDate: '2026-12-15',
    paidDate: '2026-12-14',
    status: 'pago',
    paymentMethod: 'pix',
  },
  {
    id: 'p2',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi1',
    vendorId: 'vd1',
    installmentNumber: 2,
    totalInstallments: 3,
    amount: 19200,
    dueDate: '2027-05-15',
    paidDate: '2027-05-10',
    status: 'pago',
    paymentMethod: 'transferencia',
  },
  {
    id: 'p3',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi1',
    vendorId: 'vd1',
    installmentNumber: 3,
    totalInstallments: 3,
    amount: 19200,
    dueDate: '2027-10-01',
    status: 'pendente',
    paymentMethod: 'pix',
  },
  {
    id: 'p4',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi2',
    vendorId: 'vd2',
    installmentNumber: 1,
    totalInstallments: 2,
    amount: 7500,
    dueDate: '2027-03-10',
    paidDate: '2027-03-08',
    status: 'pago',
    paymentMethod: 'pix',
  },
  {
    id: 'p5',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi2',
    vendorId: 'vd2',
    installmentNumber: 2,
    totalInstallments: 2,
    amount: 5000,
    dueDate: '2027-10-10',
    status: 'pendente',
    paymentMethod: 'pix',
  },
];

export const demoTimeline: TimelineItem[] = [
  {
    id: 'tl1',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '11:00',
    durationMinutes: 240,
    title: 'Início da Preparação dos Noivos',
    location: 'Suíte Principal - Espaço Celebração',
    responsiblePerson: 'Equipe de Beleza & Cerimonial',
    instructions: 'Chegada da equipe de beleza e fotógrafo para making of.',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'familiar'],
  },
  {
    id: 'tl2',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '15:30',
    durationMinutes: 45,
    title: 'Recepção dos Convidados na Pergola',
    location: 'Jardim Principal',
    responsiblePerson: 'Equipe de Recepção & Segurança',
    instructions: 'Servir welcome drink (água aromatizada e espumante brut). Música ambiente instrumental.',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor', 'colaborador'],
  },
  {
    id: 'tl3',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '16:30',
    durationMinutes: 50,
    title: 'Início Impecável da Cerimônia Religiosa/Simbólica',
    location: 'Altar Principal',
    responsiblePerson: 'Celebrante & Cerimonial',
    instructions: 'Entrada dos Padrinhos (Música 1), Noivo com Mãe (Música 2), Dama e Pajem (Música 3), Entrada da Noiva (Música 4).',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor', 'colaborador', 'convidado'],
  },
  {
    id: 'tl4',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '17:30',
    durationMinutes: 30,
    title: 'Sessão de Fotos de Protocolo com Padrinhos e Pais',
    location: 'Jardim Principal',
    responsiblePerson: 'Gabriel (Lumina Fotografia) & Cerimonial',
    instructions: 'Seguir estritamente a Shot List priorizada para liberar convidados para o Coquetel.',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor'],
  },
  {
    id: 'tl5',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '18:15',
    durationMinutes: 45,
    title: 'Entrada Triunfal do Casal na Festa & Primeira Dança',
    location: 'Salão Principal / Pista',
    responsiblePerson: 'DJ & Banda',
    instructions: 'Vozes e brinde dos noivos, seguidos da Dança do Casal.',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor', 'convidado'],
  },
];

export const demoDocuments: Document[] = [
  {
    id: 'doc1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Contrato Espaço Celebração - Espaço & Gastronomia.pdf',
    category: 'contrato',
    fileUrl: '/docs/contrato_espaco_celebracao.pdf',
    fileName: 'Contrato_Espaco_Celebracao_Assinado.pdf',
    fileSize: 2450000,
    tags: ['buffet', 'espaco', 'contrato_principal'],
    uploadedAt: '2026-12-15',
    parsedSummary: {
      parties: 'Espaço Celebração & Gastronomia LTDA e Alex Silva / Taylor Santos',
      totalValue: 57600,
      paymentTerms: 'Entrada de 33% + 2 parcelas iguais',
      keyDeliverables: ['Espaço por 8 horas', 'Buffet 4 tempos para 180 pessoas', 'Gerador 150 kva'],
      cancellationPenalty: '20% até 90 dias antes do evento.',
    },
  },
  {
    id: 'doc2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Certidão de Habilitação do Casamento Civil.pdf',
    category: 'certidao',
    fileUrl: '/docs/certidao_habilitacao.pdf',
    fileName: 'Habilitacao_Cartorio.pdf',
    fileSize: 1200000,
    tags: ['cartorio', 'civil', 'documentos_oficiais'],
    uploadedAt: '2027-05-10',
  },
];

export const demoGifts: Gift[] = [
  {
    id: 'gf1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Cota Lua de Mel - Jantar Romântico',
    category: 'cota',
    price: 450,
    giverName: 'Tia Carmen e Família',
    giverMessage: 'Desejamos toda a felicidade do mundo a vocês dois! Que essa viagem seja inesquecível!',
    purchased: true,
    purchasedAt: '2027-06-20',
    thanked: true,
  },
  {
    id: 'gf2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Passeio Turístico para o Casal',
    category: 'experiencia',
    price: 1200,
    giverName: 'Padrinhos Lucas & Camila',
    giverMessage: 'Aproveitem muito! Um abraço carinhoso dos seus padrinhos!',
    purchased: true,
    purchasedAt: '2027-07-02',
    thanked: false,
  },
  {
    id: 'gf3',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Jogo de Taças de Cristal (12 peças)',
    category: 'produto',
    price: 680,
    purchased: false,
    thanked: false,
  },
];

export const demoPhotoShots: PhotoShot[] = [
  { id: 'ps1', workspaceId: DEMO_WORKSPACE_ID, moment: 'pre_cerimonia', title: 'Making of dos Noivos com os Pais', peopleInvolved: 'Casal & Pais', priority: 'alta', taken: true },
  { id: 'ps2', workspaceId: DEMO_WORKSPACE_ID, moment: 'cerimonia', title: 'Troca de Alianças e Olhar Emocionado dos Noivos', peopleInvolved: 'Alex & Taylor', priority: 'alta', taken: false },
  { id: 'ps3', workspaceId: DEMO_WORKSPACE_ID, moment: 'protocolo_familia', title: 'Foto Oficial com Todos os Padrinhos e Madrinhas', peopleInvolved: 'Padrinhos, Madrinhas e Casal', priority: 'alta', taken: false },
];

export const demoNotifications: Notification[] = [
  {
    id: 'n1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Vencimento de Parcela Próximo',
    message: 'A parcela 3 do contrato do Espaço Celebração vence em breve (R$ 19.200,00).',
    type: 'vencimento',
    read: false,
    createdAt: '2027-07-25',
  },
  {
    id: 'n2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Novo RSVP Confirmado',
    message: 'Roberto Silva e Helena Silva confirmaram presença para a cerimônia e festa.',
    type: 'rsvp',
    read: true,
    createdAt: '2027-07-24',
  },
];

export const demoActivityLog: ActivityLog[] = [
  {
    id: 'act1',
    workspaceId: DEMO_WORKSPACE_ID,
    userId: 'user-2',
    userName: 'Taylor Santos',
    action: 'Confirmação de RSVP',
    details: 'Confirmou presença da família Silva com 1 restrição alimentar cadastrada.',
    timestamp: '2027-07-24 14:32',
  },
  {
    id: 'act2',
    workspaceId: DEMO_WORKSPACE_ID,
    userId: 'user-1',
    userName: 'Alex Silva',
    action: 'Atualização de Paleta',
    details: 'Adicionou o tom Grafite Carvão (#1E293B) à paleta oficial de estilo.',
    timestamp: '2027-07-22 18:10',
  },
];
