import {
  CoupleProfile,
  Guest,
  Household,
  Task,
  Vendor,
  BudgetItem,
  Payment,
  Palette,
  Outfit,
  Venue,
  Table,
  Seat,
  TimelineItem,
  Document,
  Gift,
  PhotoShot,
  ActivityLog,
  Notification
} from '../types';

export const DEMO_WORKSPACE_ID = 'ws-matheus-virginia-2026';

export const demoCoupleProfile: CoupleProfile = {
  workspaceId: DEMO_WORKSPACE_ID,
  partner1Name: 'Matheus Sousa',
  partner2Name: 'Virginia Mendes',
  coverImageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
  weddingDate: '2026-11-14',
  weddingTime: '16:30',
  timezone: 'America/Sao_Paulo',
  city: 'Campos do Jordão',
  state: 'SP',
  weddingType: 'civil_e_religioso',
  estimatedGuestsCount: 180,
  totalBudgetPlanned: 135000,
  financialResponsibles: ['Casal (60%)', 'Pais da Noiva (25%)', 'Pais do Noivo (15%)'],
  style: 'Botânico Chic & Sofisticado',
  formalityLevel: 'Semi-Formal',
  priorities: ['Gastronomia & Open Bar', 'Fotografia & Filmagem', 'Música & Pista Viva', 'Decoração Floral'],
  culturalTraditions: 'Cerimônia das Areias e Bênção das Alianças pelos Avós',
  accessibilityNeeds: 'Rampa de acesso ao altar e 2 convidados cadeirantes com mesas próximas ao banheiro acessível',
  availableWeeklyHours: 8,
  customSlug: 'matheus-virginia-2026',
  status: 'active',
};

export const demoPalette: Palette = {
  workspaceId: DEMO_WORKSPACE_ID,
  colors: [
    {
      id: 'c1',
      name: 'Marsala Profundo',
      hex: '#8B263E',
      rgb: '139, 38, 62',
      role: 'principal',
      appliedTo: ['Flores do Altar', 'Batom da Noiva', 'Detalhes da Papelaria', 'Laços dos Guardanapos'],
    },
    {
      id: 'c2',
      name: 'Dusty Rose / Rosa Antigo',
      hex: '#C48B9F',
      rgb: '196, 139, 159',
      role: 'secundaria',
      appliedTo: ['Vestidos das Madrinhas', 'Arranjos da Mesa de Doces', 'Velas da Recepção'],
    },
    {
      id: 'c3',
      name: 'Grafite Carvão',
      hex: '#1E293B',
      rgb: '30, 41, 59',
      role: 'acento',
      appliedTo: ['Terno do Noivo', 'Tipografia dos Convites', 'Estrutura dos Lustres'],
    },
    {
      id: 'c4',
      name: 'Azul-Marinho Clássico',
      hex: '#1A2536',
      rgb: '26, 37, 54',
      role: 'secundaria',
      appliedTo: ['Trajes dos Padrinhos', 'Gravatas', 'Toalhas da Mesa dos Pais'],
    },
    {
      id: 'c5',
      name: 'Verde Sálvia',
      hex: '#5B7065',
      rgb: '91, 112, 101',
      role: 'neutra',
      appliedTo: ['Foliagens de Eucalipto', 'Fundo do Site Público', 'Menus das Mesas'],
    },
    {
      id: 'c6',
      name: 'Amarelo Neon Proibido',
      hex: '#FFFF00',
      rgb: '255, 255, 0',
      role: 'proibida',
      appliedTo: ['Nenhum elemento decorativo'],
    },
  ],
  primaryTypography: 'Playfair Display',
  secondaryTypography: 'Plus Jakarta Sans',
  photoStyleDescription: 'Fotografia com iluminação natural acolhedora, tons quentes e poéticos, estilo fotojornalístico documental.',
  texturesAndMaterials: ['Linho puro cru', 'Madeira nobre de demolição', 'Metais em dourado fosco', 'Velas de cera vegetal'],
  visualVoiceTone: 'Romântico, acolhedor, sofisticado sem ostentação e extremamente inclusivo.',
};

export const demoVenues: Venue[] = [
  {
    id: 'v1',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Quinta das Flores Eventos',
    type: 'ambos',
    address: 'Av. das Hortênsias, 1200 - Alto da Boa Vista',
    city: 'Campos do Jordão',
    state: 'SP',
    seatedCapacity: 220,
    standingCapacity: 300,
    hasParking: true,
    valetAvailable: true,
    restroomsCount: 8,
    hasNursery: true,
    hasKitchen: true,
    hasDressingRoom: true,
    generatorPowerKva: 150,
    airConditioning: true,
    accessibleRoute: true,
    weatherBackupPlan: 'Pergola envidraçada climatizada integrada para a cerimônia em caso de chuva forte.',
    noiseRestrictions: 'Som reduzido após às 03:00h.',
    rentalFee: 24000,
    notes: 'Local com vista deslumbrante para a serra e suíte completa para o Dia da Noiva.',
  },
];

export const demoOutfits: Outfit[] = [
  {
    id: 'o1',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Virginia Mendes (Noiva)',
    role: 'noiva',
    color: 'Off-White Ivory',
    itemDescription: 'Vestido fluído em zibelina de seda com decote ombro a ombro e cauda removível',
    rentalOrBuy: 'compra',
    totalCost: 9800,
    paidBy: 'Noiva',
    sizesAndMeasurements: 'Busto: 88cm | Cintura: 68cm | Quadril: 96cm | Altura: 1,68m',
    status: 'em_ajuste',
    imageUrl: 'https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&w=600&q=80',
    accessoriesNotes: 'Véu de tule francês 3m com aplicação de renda guipure + Grinalda em zircônia e pérolas',
  },
  {
    id: 'o2',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Matheus Sousa (Noivo)',
    role: 'noivo',
    color: 'Carvão Grafite',
    itemDescription: 'Terno slim fit sob medida em lã fria Super 130s com colete e camisa de algodão egípcio',
    rentalOrBuy: 'compra',
    totalCost: 4500,
    paidBy: 'Noivo',
    sizesAndMeasurements: 'Terno 48L | Camisa 3 | Sapato 41',
    status: 'pronto',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    accessoriesNotes: 'Gravata borboleta marsala + Abotoaduras em prata e flor de lapela com mini orquídea',
  },
  {
    id: 'o3',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Madrinhas (8 participantes)',
    role: 'madrinha',
    color: 'Dusty Rose / Rosa Antigo (#C48B9F)',
    itemDescription: 'Vestidos longos no tom rosa antigo (modelo livre à escolha da madrinha)',
    rentalOrBuy: 'proprio',
    totalCost: 0,
    paidBy: 'Madrinhas',
    sizesAndMeasurements: 'Guia de tons entregue no Manual dos Padrinhos',
    status: 'escolhido',
    accessoriesNotes: 'Corsage floral idêntico fornecido pela cerimonialista no dia',
  },
  {
    id: 'o4',
    workspaceId: DEMO_WORKSPACE_ID,
    participantName: 'Padrinhos (8 participantes)',
    role: 'padrinho',
    color: 'Azul-Marinho Clássico (#1A2536)',
    itemDescription: 'Terno completo azul-marinho + Camisa branca + Gravata marsala padronizada',
    rentalOrBuy: 'aluguel',
    totalCost: 2400,
    paidBy: 'Padrinhos',
    sizesAndMeasurements: 'Aluguel com desconto na loja parceira Camargo Alfaiataria',
    status: 'escolhido',
    accessoriesNotes: 'Gravata marsala presenteada pelo casal',
  },
];

export const demoHouseholds: Household[] = [
  { id: 'h1', workspaceId: DEMO_WORKSPACE_ID, familyName: 'Família Mendes (Noiva)', city: 'São Paulo - SP' },
  { id: 'h2', workspaceId: DEMO_WORKSPACE_ID, familyName: 'Família Sousa (Noivo)', city: 'Campinas - SP' },
  { id: 'h3', workspaceId: DEMO_WORKSPACE_ID, familyName: 'Casal Padrinhos Lucas & Camila', city: 'São Paulo - SP' },
];

export const demoGuests: Guest[] = [
  {
    id: 'g1',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h1',
    fullName: 'Roberto Mendes',
    relationship: 'familia_noiva',
    category: 'pais',
    phone: '(11) 99887-1122',
    email: 'roberto.mendes@email.com',
    ageType: 'adulto',
    invitationType: 'familiar',
    allowedPlusOnes: 1,
    plusOneNames: ['Helena Mendes'],
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's1',
    qrCodeToken: 'QR-MENDES-ROBERTO-001',
    checkedIn: false,
    notes: 'Pai da noiva - discurso no brinde.',
  },
  {
    id: 'g2',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h1',
    fullName: 'Helena Mendes',
    relationship: 'familia_noiva',
    category: 'pais',
    phone: '(11) 99887-1133',
    email: 'helena.mendes@email.com',
    ageType: 'adulto',
    invitationType: 'familiar',
    allowedPlusOnes: 0,
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's2',
    qrCodeToken: 'QR-MENDES-HELENA-002',
    checkedIn: false,
    notes: 'Mãe da noiva - restrição a frutos do mar.',
  },
  {
    id: 'g3',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h2',
    fullName: 'Carlos Eduardo Sousa',
    relationship: 'familia_noivo',
    category: 'pais',
    phone: '(19) 98765-4321',
    email: 'carlos.sousa@email.com',
    ageType: 'adulto',
    invitationType: 'familiar',
    allowedPlusOnes: 1,
    plusOneNames: ['Márcia Sousa'],
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's3',
    qrCodeToken: 'QR-SOUSA-CARLOS-003',
    checkedIn: false,
  },
  {
    id: 'g4',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h3',
    fullName: 'Lucas Gabriel',
    relationship: 'amigos',
    category: 'padrinho',
    phone: '(11) 97112-3344',
    email: 'lucas.gabriel@email.com',
    ageType: 'adulto',
    invitationType: 'individual',
    allowedPlusOnes: 1,
    plusOneNames: ['Camila Rocha'],
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't2',
    seatId: 's5',
    qrCodeToken: 'QR-LUCAS-GABRIEL-004',
    checkedIn: false,
    notes: 'Padrinho do noivo - vegetariano.',
  },
  {
    id: 'g5',
    workspaceId: DEMO_WORKSPACE_ID,
    householdId: 'h3',
    fullName: 'Camila Rocha',
    relationship: 'amigos',
    category: 'madrinha',
    phone: '(11) 97112-3355',
    email: 'camila.rocha@email.com',
    ageType: 'adulto',
    invitationType: 'individual',
    allowedPlusOnes: 0,
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't2',
    seatId: 's6',
    qrCodeToken: 'QR-CAMILA-ROCHA-005',
    checkedIn: false,
    notes: 'Madrinha da noiva.',
  },
  {
    id: 'g6',
    workspaceId: DEMO_WORKSPACE_ID,
    fullName: 'Dona Beatris Mendes',
    relationship: 'familia_noiva',
    category: 'vip',
    phone: '(11) 96655-4433',
    ageType: 'adulto',
    invitationType: 'individual',
    allowedPlusOnes: 0,
    status: 'confirmado',
    eventsPermitted: ['ev1', 'ev2'],
    tableId: 't1',
    seatId: 's4',
    qrCodeToken: 'QR-BEATRIS-MENDES-006',
    checkedIn: false,
    notes: 'Avó da noiva - necessita de rampa de acesso e assento estofado confortável.',
  },
];

export const demoTables: Table[] = [
  {
    id: 't0',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Mesa Imperial dos Noivos',
    shape: 'imperial',
    capacity: 2,
    posX: 50,
    posY: 20,
    zone: 'noivos',
  },
  {
    id: 't1',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Mesa 01 - Pais & Avós',
    shape: 'redonda',
    capacity: 8,
    posX: 25,
    posY: 40,
    zone: 'salao_principal',
  },
  {
    id: 't2',
    workspaceId: DEMO_WORKSPACE_ID,
    name: 'Mesa 02 - Padrinhos & Madrinhas',
    shape: 'retangular',
    capacity: 10,
    posX: 75,
    posY: 40,
    zone: 'pista',
  },
];

export const demoTasks: Task[] = [
  {
    id: 'tk1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Fechar contrato do Espaço & Buffet Quinta das Flores',
    category: 'Local & Gastronomia',
    assignedToUserIds: ['user-1'],
    startDate: '2025-11-01',
    dueDate: '2025-12-15',
    priority: 'urgente',
    status: 'concluida',
    estimatedCost: 65000,
    subtasks: [
      { id: 'st1', title: 'Degustação do menu de 4 tempos', completed: true },
      { id: 'st2', title: 'Conferir cláusulas de chuva no plano B', completed: true },
      { id: 'st3', title: 'Assinar contrato digital', completed: true },
    ],
    attachmentsCount: 2,
    commentsCount: 4,
    monthsBeforeWedding: 12,
  },
  {
    id: 'tk2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Aprovar identidade visual e disparar Save the Date',
    category: 'Papelaria & Design',
    assignedToUserIds: ['user-1', 'user-2'],
    startDate: '2026-02-01',
    dueDate: '2026-03-30',
    priority: 'alta',
    status: 'concluida',
    estimatedCost: 2800,
    subtasks: [
      { id: 'st4', title: 'Definir paleta Marsala/Dusty Rose/Grafite', completed: true },
      { id: 'st5', title: 'Aprovar arte no Estúdio de Identidade', completed: true },
      { id: 'st6', title: 'Enviar Save the Date via WhatsApp e E-mail', completed: true },
    ],
    attachmentsCount: 3,
    commentsCount: 2,
    monthsBeforeWedding: 8,
  },
  {
    id: 'tk3',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Segunda prova do vestido da noiva e teste de make',
    category: 'Vestuário & Beleza',
    assignedToUserIds: ['user-2'],
    startDate: '2026-08-10',
    dueDate: '2026-08-25',
    priority: 'alta',
    status: 'em_andamento',
    estimatedCost: 9800,
    subtasks: [
      { id: 'st7', title: 'Ajustar barra com sapato oficial', completed: false },
      { id: 'st8', title: 'Levar véu de 3 metros no ateliê', completed: true },
      { id: 'st9', title: 'Teste de durabilidade da maquiagem', completed: false },
    ],
    attachmentsCount: 1,
    commentsCount: 1,
    monthsBeforeWedding: 3,
  },
  {
    id: 'tk4',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Definir lista final de músicas da cerimônia e festa',
    category: 'Música & Pista',
    assignedToUserIds: ['user-1'],
    startDate: '2026-09-01',
    dueDate: '2026-09-30',
    priority: 'media',
    status: 'em_pesquisa',
    estimatedCost: 8500,
    subtasks: [
      { id: 'st10', title: 'Escolher música de entrada da noiva', completed: true },
      { id: 'st11', title: 'Criar playlist de proibições (No-Play List)', completed: false },
    ],
    attachmentsCount: 0,
    commentsCount: 3,
    monthsBeforeWedding: 2,
  },
];

export const demoVendors: Vendor[] = [
  {
    id: 'vd1',
    workspaceId: DEMO_WORKSPACE_ID,
    category: 'Espaço & Buffet',
    legalName: 'Quinta das Flores Gastronomia EIRELI',
    tradeName: 'Quinta das Flores Eventos',
    documentNumber: '12.345.678/0001-90',
    contactPerson: 'Juliana Camargo',
    phone: '(12) 99776-5544',
    email: 'contato@quintadasflores.com.br',
    city: 'Campos do Jordão - SP',
    status: 'contratado',
    rating: 5,
    pros: 'Gastronomia espetacular, equipe impecável e plano B coberto muito elegante.',
    cons: 'Exige gerador próprio acima de 100 kva (já incluso no orçamento).',
    emergencyPhone: '(12) 99776-5500',
  },
  {
    id: 'vd2',
    workspaceId: DEMO_WORKSPACE_ID,
    category: 'Fotografia & Filmagem',
    legalName: 'Lumina Arte Visual Ltda',
    tradeName: 'Lumina Fotografia Poética',
    documentNumber: '98.765.432/0001-10',
    contactPerson: 'Gabriel Resende',
    phone: '(11) 98822-1100',
    email: 'contato@luminafotografia.com',
    city: 'São Paulo - SP',
    status: 'contratado',
    rating: 5,
    pros: 'Estilo documental único, entregam prévia de 50 fotos em 48 horas.',
    emergencyPhone: '(11) 98822-1199',
  },
  {
    id: 'vd3',
    workspaceId: DEMO_WORKSPACE_ID,
    category: 'Decoração Floral',
    legalName: 'Estúdio Botânico Design Floral',
    tradeName: 'Botânica Arte & Festas',
    documentNumber: '44.555.666/0001-22',
    contactPerson: 'Marina Prado',
    phone: '(11) 99123-8899',
    email: 'marina@botanicadesign.com',
    city: 'São Paulo - SP',
    status: 'negociacao',
    rating: 4,
    pros: 'Trabalho minucioso com orquídeas e eucaliptos na paleta Marsala.',
  },
];

export const demoBudgetItems: BudgetItem[] = [
  {
    id: 'bi1',
    workspaceId: DEMO_WORKSPACE_ID,
    categoryId: 'cat-1',
    description: 'Locação do Espaço Quinta das Flores + Buffet Completo (180 pess)',
    vendorId: 'vd1',
    quantity: 180,
    unitPrice: 320,
    estimatedCost: 60000,
    negotiatedCost: 57600,
    contractedCost: 57600,
    paidAmount: 38400,
    payerName: 'Casal (60%)',
    notes: 'Incluso coquetel volante, jantar 4 tempos, bar de drinks clássicos e mesa de café.',
  },
  {
    id: 'bi2',
    workspaceId: DEMO_WORKSPACE_ID,
    categoryId: 'cat-2',
    description: 'Cobertura de Fotografia + Filme Teaser + Drone (2 fotógrafos + 2 videomakers)',
    vendorId: 'vd2',
    quantity: 1,
    unitPrice: 12500,
    estimatedCost: 13000,
    negotiatedCost: 12500,
    contractedCost: 12500,
    paidAmount: 7500,
    payerName: 'Pais da Noiva',
  },
  {
    id: 'bi3',
    workspaceId: DEMO_WORKSPACE_ID,
    categoryId: 'cat-3',
    description: 'Projeto Decorativo Floral Completo (Altar, Mesas, Lounge & Iluminação Cênica)',
    vendorId: 'vd3',
    quantity: 1,
    unitPrice: 22000,
    estimatedCost: 25000,
    negotiatedCost: 22000,
    contractedCost: 22000,
    paidAmount: 5000,
    payerName: 'Casal',
  },
];

export const demoPayments: Payment[] = [
  {
    id: 'p1',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi1',
    vendorId: 'vd1',
    installmentNumber: 1,
    totalInstallments: 3,
    amount: 19200,
    dueDate: '2025-12-15',
    paidDate: '2025-12-14',
    status: 'pago',
    paymentMethod: 'pix',
  },
  {
    id: 'p2',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi1',
    vendorId: 'vd1',
    installmentNumber: 2,
    totalInstallments: 3,
    amount: 19200,
    dueDate: '2026-05-15',
    paidDate: '2026-05-10',
    status: 'pago',
    paymentMethod: 'transferencia',
  },
  {
    id: 'p3',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi1',
    vendorId: 'vd1',
    installmentNumber: 3,
    totalInstallments: 3,
    amount: 19200,
    dueDate: '2026-10-30',
    status: 'pendente',
    paymentMethod: 'pix',
  },
  {
    id: 'p4',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi2',
    vendorId: 'vd2',
    installmentNumber: 1,
    totalInstallments: 2,
    amount: 7500,
    dueDate: '2026-03-10',
    paidDate: '2026-03-08',
    status: 'pago',
    paymentMethod: 'pix',
  },
  {
    id: 'p5',
    workspaceId: DEMO_WORKSPACE_ID,
    budgetItemId: 'bi2',
    vendorId: 'vd2',
    installmentNumber: 2,
    totalInstallments: 2,
    amount: 5000,
    dueDate: '2026-11-01',
    status: 'pendente',
    paymentMethod: 'pix',
  },
];

export const demoTimeline: TimelineItem[] = [
  {
    id: 'tl1',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '11:00',
    durationMinutes: 240,
    title: 'Início do Dia da Noiva & Maquiagem',
    location: 'Suíte Master - Quinta das Flores',
    responsiblePerson: 'Virginia & Cerimonial',
    instructions: 'Chegada da equipe de beleza (Studio Bella) e fotógrafo para making of.',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'familiar'],
  },
  {
    id: 'tl2',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '15:30',
    durationMinutes: 45,
    title: 'Chegada e Recepção dos Convidados na Pergola',
    location: 'Jardim das Hortênsias',
    responsiblePerson: 'Equipe de Recepção & Segurança',
    instructions: 'Servir welcome drink (água aromatizada e espumante brut). Música ambiente instrumental.',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor', 'colaborador'],
  },
  {
    id: 'tl3',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '16:30',
    durationMinutes: 50,
    title: 'Início Imprecável da Cerimônia Religiosa/Simbólica',
    location: 'Altar da Quinta das Flores',
    responsiblePerson: 'Celebrante Padre André & Cerimonial',
    instructions: 'Entrada dos Padrinhos (Música 1), Noivo com Mãe (Música 2), Dama e Pajem (Música 3), Entrada da Noiva (Música 4).',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor', 'colaborador', 'convidado'],
  },
  {
    id: 'tl4',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '17:30',
    durationMinutes: 30,
    title: 'Sessão de Fotos de Protocolo com Padrinhos e Pais',
    location: 'Jardim Principal',
    responsiblePerson: 'Gabriel (Lumina Fotografia) & Cerimonial',
    instructions: 'Seguir estritamente a Shot List priorizada para liberar convidados para o Coquetel.',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor'],
  },
  {
    id: 'tl5',
    workspaceId: DEMO_WORKSPACE_ID,
    time: '18:15',
    durationMinutes: 45,
    title: 'Entrada Triunfal do Casal na Festa & Primeira Dança',
    location: 'Salão Principal / Pista',
    responsiblePerson: 'DJ Rodrigo & Banda Soul',
    instructions: 'Vozes e brinde dos noivos, seguidos da Dança do Casal (Música: "You Are The Reason").',
    visibleToProfiles: ['casal_admin', 'cerimonialista', 'fornecedor', 'convidado'],
  },
];

export const demoDocuments: Document[] = [
  {
    id: 'doc1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Contrato Quinta das Flores - Espaço & Gastronomia.pdf',
    category: 'contrato',
    fileUrl: '/docs/contrato_quinta_flores.pdf',
    fileName: 'Contrato_Quinta_Flores_Assinado.pdf',
    fileSize: 2450000,
    tags: ['buffet', 'espaco', 'contrato_principal'],
    uploadedAt: '2025-12-15',
    parsedSummary: {
      parties: 'Quinta das Flores Gastronomia EIRELI e Matheus Sousa / Virginia Mendes',
      totalValue: 57600,
      paymentTerms: 'Entrada de 33% + 2 parcelas iguais',
      keyDeliverables: ['Espaço por 8 horas', 'Buffet 4 tempos para 180 pessoas', 'Gerador 150 kva'],
      cancellationPenalty: '20% até 90 dias antes do evento.',
    },
  },
  {
    id: 'doc2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Certidão de Habilitação do Casamento Civil.pdf',
    category: 'certidao',
    fileUrl: '/docs/certidao_habiliter.pdf',
    fileName: 'Habilitacao_Cartorio_CamposJordao.pdf',
    fileSize: 1200000,
    tags: ['cartorio', 'civil', 'documentos_oficiais'],
    uploadedAt: '2026-06-10',
  },
];

export const demoGifts: Gift[] = [
  {
    id: 'gf1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Cota Lua de Mel - Jantar Romântico nas Falésias de Santorini',
    category: 'cota',
    price: 450,
    giverName: 'Tia Carmen e Família',
    giverMessage: 'Desejamos toda a felicidade do mundo a vocês dois! Que essa viagem seja inesquecível!',
    purchased: true,
    purchasedAt: '2026-06-20',
    thanked: true,
  },
  {
    id: 'gf2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Passeio de Balão na Capadócia para o Casal',
    category: 'experiencia',
    price: 1200,
    giverName: 'Padrinhos Lucas & Camila',
    giverMessage: 'Aproveitem muito as alturas! Um abraço carinhoso dos seus padrinhos!',
    purchased: true,
    purchasedAt: '2026-07-02',
    thanked: false,
  },
  {
    id: 'gf3',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Jogo de Taças de Cristal de Bohemia (12 peças)',
    category: 'produto',
    price: 680,
    purchased: false,
    thanked: false,
  },
];

export const demoPhotoShots: PhotoShot[] = [
  { id: 'ps1', workspaceId: DEMO_WORKSPACE_ID, moment: 'pre_cerimonia', title: 'Making of Noiva com a Mãe ajustando o véu', peopleInvolved: 'Virginia & Helena Mendes', priority: 'alta', taken: true },
  { id: 'ps2', workspaceId: DEMO_WORKSPACE_ID, moment: 'cerimonia', title: 'Troca de Alianças e Olhar Emocionado dos Noivos', peopleInvolved: 'Matheus & Virginia', priority: 'alta', taken: false },
  { id: 'ps3', workspaceId: DEMO_WORKSPACE_ID, moment: 'protocolo_familia', title: 'Foto Oficial com Todos os 16 Padrinhos e Madrinhas', peopleInvolved: 'Padrinhos, Madrinhas e Casal', priority: 'alta', taken: false },
];

export const demoNotifications: Notification[] = [
  {
    id: 'n1',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Vencimento de Parcela Próximo',
    message: 'A parcela 3 do contrato Quinta das Flores vence em 30 dias (R$ 19.200,00).',
    type: 'vencimento',
    read: false,
    createdAt: '2026-07-25',
  },
  {
    id: 'n2',
    workspaceId: DEMO_WORKSPACE_ID,
    title: 'Novo RSVP Confirmado',
    message: 'Roberto Mendes e Helena Mendes confirmaram presença para a cerimônia e festa.',
    type: 'rsvp',
    read: true,
    createdAt: '2026-07-24',
  },
];

export const demoActivityLog: ActivityLog[] = [
  {
    id: 'act1',
    workspaceId: DEMO_WORKSPACE_ID,
    userId: 'user-2',
    userName: 'Virginia Mendes',
    action: 'Confirmação de RSVP',
    details: 'Confirmou presença da família Mendes com 1 restrição alimentar cadastrada.',
    timestamp: '2026-07-24 14:32',
  },
  {
    id: 'act2',
    workspaceId: DEMO_WORKSPACE_ID,
    userId: 'user-1',
    userName: 'Matheus Sousa',
    action: 'Atualização de Paleta',
    details: 'Adicionou o tom Grafite Carvão (#1E293B) à paleta oficial de estilo.',
    timestamp: '2026-07-22 18:10',
  },
];
